version: "3.9"
services:
  java_app:
    container_name: java_app
    image: pee-java_app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/store
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    depends_on:
      - java_db
    restart: on-failure
    command:
      ["./wait-for-it.sh", "java_db:5432", "--", "java", "-jar", "/app.jar"]

  java_db:
    container_name: java_db
    image: postgres:12
    environment:
      - POSTGRES_DB=store
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=diegomedina04@outlook.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d store"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
# copia:
# java_db:
#     container_name: java_db
#     image: postgres:12
#     ports:
#       - 5432:5432
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: postgres

# version: "3.3"

# services:
#   postgres:
#     image: postgres:13
#     environment:
#       - POSTGRES_DB=store
#       - POSTGRES_USER=root
#       - POSTGRES_PASSWORD=root
#     ports:
#       - 5432:5432
#     volumes:
#       - /postgres_data:/var/lib/postgresql/data

#   pgadmin:
#     image: dpage/pgadmin4
#     environment:
#       - PGADMIN_DEFAULT_EMAIL=diegomedina04@outlook.com
#       - PGADMIN_DEFAULT_PASSWORD=root
#     ports:
#       - 5050:80
#   springboot-app:
#     image: store
#     container_name: springboot_app_container
#     depends_on:
#       - postgres
#     ports:
#       - "8080:8080"
#     environment:
#       spring.datasource.url: jdbc:postgresql://postgres:5432/store
#       spring.datasource.username: root
#       spring.datasource.password: root
#       spring.jpa.hibernate.ddl-auto: update
